name: Golang Problems CI

on:
  push:
    paths:
     - go/
  workflow_dispatch:

defaults:
  run:
    working-directory: go

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
          check-latest: true
          cache: true

      - name: Run tests
        run: go test ./...
