name: Java Problems CI

on:
  push:
    paths:
     - java/**
  workflow_dispatch:


defaults:
  run:
    working-directory: java

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
